server:
  port: 8080
  servlet:
    context-path: /webmvc

lodsve:
  swagger:
    enabled: true
  web-mvc:
    is-debug: true

logging:
  level:
    com.lodsve: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - versions
          - enums
          - dependencies
  endpoint:
    health:
      show-details: always
