name: Deploy Snapshot Weekly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0'

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup JDK11 And Apache Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: 11
          cache: 'maven'
          server-id: oss-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Get And Set Version
        id: get_version
        run: |
          MVN_VERSION=$(mvn -q -N -Dexec.executable="echo"  -Dexec.args='${project.version}'  org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
          NEW_VERSION=${MVN_VERSION%-*}-$(date "+%Y%m%d")-SNAPSHOT
          ./lodsve.sh versions ${NEW_VERSION}
          echo "newVersion=$NEW_VERSION" >> $GITHUB_ENV
          echo "oldVersion=$MVN_VERSION" >> $GITHUB_ENV
      - name: Publish to Apache Maven Central
        run: |
          echo {% raw %}${{secrets.MAVEN_USERNAME }}{% endraw %} | sed 's/./& /g'
          echo {% raw %}${{secrets.MAVEN_CENTRAL_TOKEN }}{% endraw %} | sed 's/./& /g'
          echo {% raw %}${{secrets.MAVEN_GPG_PASSPHRASE }}{% endraw %} | sed 's/./& /g'
          mvn clean deploy -P release-oss-snapshot
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.LODSVE_BOOT_TOKEN }}
          tag_name: ${{ steps.get_version.outputs.newVersion }}
          prerelease: true
          body: |
            This is a pre-release. Just to try new features! Please use with caution. If you have any questions, please contact me in the issue.
            1. JavaDoc: [https://javadoc.lodsve.com](https://javadoc.lodsve.com)
            2. MyBlog: [https://www.crazy-coder.cn](https://www.crazy-coder.cn)
      - name: Reset code
        id: reset_code
        env:
          OLD_VERSION: ${{ steps.get_version.outputs.oldVersion }}
        run: |
          echo oldVersion is ${env.OLD_VERSION}
          ./lodsve.sh versions ${env.OLD_VERSION}
