name: Deploy Snapshot Weekly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0'

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup JDK11 And Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt-hotspot'
          java-version: 11
          cache: 'maven'
          server-id: oss-central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Get And Set Version
        id: get_version
        run: |
          MVN_VERSION=$(./mvnw -q -N -Dexec.executable="echo"  -Dexec.args='${project.version}'  org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
          NEW_VERSION=${MVN_VERSION%-*}-$(date "+%Y%m%d")-SNAPSHOT
          bash ./lodsve versions ${NEW_VERSION}
          echo "newVersion=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "oldVersion=$MVN_VERSION" >> $GITHUB_OUTPUT
      - id: install-secret-key
        name: Install Secret Key
        run: |
          cat <(echo -e "${{ secrets.LODSVE_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish to Apache Maven Central
        run: |
          ./mvnw --batch-mode -Dgpg.passphrase=${{ secrets.LODSVE_GPG_SECRET_KEY_PASSWORD }} clean deploy -P release-oss
          mkdir -p archives & rm -rf archives/* & find ./target/central-deferred/ -name "lodsve-boot-*.jar" -type f -not -path "./archives/*" | xargs -i cp {} ./archives/
          zip -r lodsve-boot-${{ steps.get_version.outputs.newVersion }}-archives.zip ./archives/* LICENSE README.md README.cn.md capability.md capability_cn.md CHANGELOG.md
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Upload Release Asset
        id: upload_release_asset
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.LODSVE_BOOT_TOKEN }}
          tag_name: ${{ steps.get_version.outputs.newVersion }}
          prerelease: true
          files: lodsve-boot-${{ steps.get_version.outputs.newVersion }}-archives.zip
          body: |
            This is a pre-release. Just to try new features! Please use with caution. If you have any questions, please contact me in the issue.
            1. JavaDoc: [https://javadoc.lodsve.com](https://javadoc.lodsve.com)
            2. MyBlog: [https://www.crazy-coder.cn](https://www.crazy-coder.cn)
      - name: Reset code
        id: reset_code
        env:
          OLD_VERSION: ${{ steps.get_version.outputs.oldVersion }}
          NEW_VERSION: ${{ steps.get_version.outputs.newVersion }}
        run: |
          echo oldVersion is ${OLD_VERSION}
          ./mvnw clean & rm -rf lodsve-boot-${NEW_VERSION}-archives.zip archives
          bash ./lodsve versions ${OLD_VERSION}
      - name: Send DingDing Notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          body: |
            {
              "msgtype": "link",
              "link": {
                "picUrl": "https://www.gitbook.com/cdn-cgi/image/width=256,height=40,fit=contain,dpr=1,format=auto/https%3A%2F%2F1978062287-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-legacy-files%2Fo%2Fspaces%252F-LI6IFYne1nz5hKJG9KV%252Favatar-rectangle.png%3Fgeneration%3D1569591536803744%26alt%3Dmedia",
                "text": "已发布新的快照预览版本【${{ steps.get_version.outputs.newVersion }}】，点击消息即可查看！",
                "title": "Lodsve-Boot",
                "messageUrl": "${{ steps.upload_release_asset.outputs.url }}"
              }
            }
