name: Deploy Snapshot Weekly
on:
  schedule:
    - cron: '0 23 * * 0'

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup JDK11 And Apache Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: 11
          cache: 'maven'
          server-id: oss-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Get Version
        id: get_version
        run: |
          MVN_VERSION=$(mvn -q -N -Dexec.executable="echo"  -Dexec.args='${project.version}'  org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
          echo "::set-output name=version::$MVN_VERSION"
      - name: Publish to Apache Maven Central
        run: |
          cat /home/runner/.m2/settings.xml
          mvn clean deploy -P release-oss-snapshot
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.LODSVE_BOOT_TOKEN }}
          tag_name: ${{ steps.get_version.outputs.version }}
          prerelease: true
          body: This is a pre-release. Just to try new features! Please use with caution. If you have any questions, please contact me in the issue.

